#!/bin/bash
# ========================================
# RME Linux Build Script (Clang++ + Mold + Ninja)
# Optimized for Jules AI (Low Resource)
# ========================================

set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Using local build_clang directory (gitignored)
BUILD_DIR="$SCRIPT_DIR/build_clang"
LOG_FILE="$BUILD_DIR/build_clang.log"

# Ensure build directory exists for the log file
mkdir -p "$BUILD_DIR"

# Function to run command and only show errors
run_quiet() {
    if ! "$@" >> "$LOG_FILE" 2>&1; then
        echo "Error executing: $*"
        echo "Check $LOG_FILE for details."
        exit 1
    fi
}

{
    echo "========================================"
    echo " RME Linux Optimized Build"
    echo " Started: $(date)"
    echo "========================================"
} > "$LOG_FILE"

# Step 1: Ensure fast tools are installed
echo "[1/5] Checking/Installing Tools (Quiet)..."
sudo apt update -y > /dev/null 2>&1
sudo apt install -y clang lld mold ccache ninja-build make clang-tools-18 > /dev/null 2>&1

# Step 2: Setup Conan profile for Clang if it doesn't exist
echo "[2/5] Setting up Conan Clang profile..."
if ! conan profile show -pr clang &> /dev/null; then
    run_quiet conan profile detect --name clang --force
    run_quiet conan profile exec-update -pr clang "settings.compiler.libcxx=libstdc++11"
fi

# Step 3: Install dependencies with Conan (Debug)
echo "[3/5] Installing dependencies (Debug)..."
# Setting output folder to BUILD_DIR to keep git root clean
run_quiet conan install "$SCRIPT_DIR" \
    -pr:b=default \
    -pr:h=clang \
    -of "$BUILD_DIR" \
    --build=missing \
    -s build_type=Debug \
    -c tools.system.package_manager:mode=install \
    -c tools.system.package_manager:sudo=True

# Step 4: Configure CMake with Clang++, Mold, Ninja
echo "[4/5] Configuring CMake (Ninja + Mold)..."
export CC=clang
export CXX=clang++

# Speed tactics:
# -O0 -g0 for fastest possible compilation (skips optimizations & symbols)
# -fuse-ld=mold for near-instant linking
# CMAKE_UNITY_BUILD=OFF to support ccache and incremental builds
# CMAKE_CXX_COMPILER_LAUNCHER=ccache for robust caching

# Path to toolchain generated by Conan
TOOLCHAIN_FILE="$BUILD_DIR/build/Debug/generators/conan_toolchain.cmake"

# Re-configure from scratch if generator mismatch
if [ -d "$BUILD_DIR/build/Debug" ] && [ -f "$BUILD_DIR/build/Debug/CMakeCache.txt" ]; then
    if ! grep -q "CMAKE_GENERATOR:INTERNAL=Ninja" "$BUILD_DIR/build/Debug/CMakeCache.txt"; then
        rm -rf "$BUILD_DIR/build/Debug"
    fi
fi

# Explicitly point to clang-scan-deps for C++23 modules/dependency scanning in Ninja
SCAN_DEPS=$(which clang-scan-deps-18 || which clang-scan-deps || echo "")

run_quiet cmake -S "$SCRIPT_DIR" -B "$BUILD_DIR/build/Debug" \
    -G "Ninja" \
    --log-level=ERROR \
    -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN_FILE" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_CXX_FLAGS_DEBUG="-O0 -g0" \
    -DCMAKE_C_FLAGS_DEBUG="-O0 -g0" \
    -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" \
    -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold" \
    -DCMAKE_MODULE_LINKER_FLAGS="-fuse-ld=mold" \
    -DCMAKE_UNITY_BUILD=OFF \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_CLANG_SCAN_DEPS="$SCAN_DEPS"

# Step 5: Building with Ninja (Output to screen AND log)
echo "[5/5] Building with Ninja (j2 to avoid OOM)..." | tee -a "$LOG_FILE"

if ! ninja -C "$BUILD_DIR/build/Debug" -j2 2>&1 | tee -a "$LOG_FILE"; then
    echo "========================================" | tee -a "$LOG_FILE"
    echo " BUILD FAILED. COPY THE ERRORS ABOVE TO THE AI." | tee -a "$LOG_FILE"
    echo "========================================" | tee -a "$LOG_FILE"
    exit 1
fi

{
    echo "========================================"
    echo " BUILD SUCCESSFUL (DEBUG + NINJA + MOLD)"
    echo " Output: $BUILD_DIR/build/Debug/rme"
    echo " Finished: $(date)"
    echo "========================================"
} >> "$LOG_FILE"

echo "========================================"
echo " BUILD SUCCESSFUL!"
echo " Mode: Debug (-O0 -g0)"
echo " Parallel: 2 jobs"
echo " Linker: Mold"
echo " Output: $BUILD_DIR/build/Debug/rme"
echo "========================================"
