[editor]
always_make_backup = false
auto_assign_doorid = true
auto_create_spawn = true
border_is_ground = true
borderize_drag = true
borderize_drag_threshold = 6000
borderize_paste = true
borderize_paste_threshold = 10000
compensated_select = true
copy_position_format = 0
current_spawn_radius = 5
default_client_version = 1
default_spawntime = 60
doodad_brush_erase_like = false
doubleclick_properties = true
eraser_leave_unique = true
find_item_mode = 0
group_actions = true
house_brush_remove_items = false
jump_to_item_mode = 0
listbox_eats_all_events = true
max_spawn_radius = 30
merge_move = false
merge_paste = false
only_one_instance = true
raw_like_simone = true
recent_edited_map_path = ''
recent_edited_map_position = ''
recent_files = [ 'C:\Users\karol\Downloads\karmia-tfs(1)\karmia.otbm' ]
replace_size = 500
save_with_otb_magic_number = false
scroll_speed = 3.5
selection_type = 0
show_tileset_editor = false
switch_mousebuttons = false
undo_mem_size = 40
undo_size = 400
use_automagic = true
use_otbm_4_for_all_maps = false
warn_for_duplicate_id = true
worker_threads = 1
zoom_speed = 1.399999976158142

[experimental]
experimental_fog = 0

[general]
autocheck_for_updates = false
goto_website_on_boot = false
use_updater = true

[graphics]
anti_aliasing = 0
cursor_alpha = 128
cursor_alt_alpha = 128
cursor_alt_blue = 0
cursor_alt_green = 166
cursor_alt_red = 0
cursor_blue = 0
cursor_green = 166
cursor_red = 0
frame_rate_limit = 144
hard_refresh_rate = 200
hide_items_when_zoomed = true
icon_background = 0
minimap_export_dir = ''
minimap_update_delay = 333
minimap_view_box = true
screen_shader = 'None'
screenshot_directory = 'C:\Users\karol\Pictures\RME\'
screenshot_format = 'png'
show_fps_counter = false
software_clean_size = 500
software_clean_threshold = 1800
texture_clean_pulse = 15
texture_clean_threshold = 2500
texture_longevity = 20
texture_management = true
tileset_export_dir = ''
use_memcached_sprites = 0

[hotkeys]
hotkey_0 = 'NONE'
hotkey_1 = 'NONE'
hotkey_2 = 'NONE'
hotkey_3 = 'NONE'
hotkey_4 = 'NONE'
hotkey_5 = 'NONE'
hotkey_6 = 'NONE'
hotkey_7 = 'NONE'
hotkey_8 = 'NONE'
hotkey_9 = 'NONE'
numerical_hotkeys = ''

[toolbars]
show_toolbar_brushes = false
show_toolbar_position = false
show_toolbar_sizes = false
show_toolbar_standard = true
toolbar_brushes_layout = ''
toolbar_position_layout = ''
toolbar_sizes_layout = ''
toolbar_standard_layout = 'name=standard_toolbar;caption=;state=2106044;dir=1;layer=10;row=1;pos=1;prop=100000;bestw=282;besth=26;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1;floatw_cli=-1;floath_cli=-1'

[ui]
palette_col_count = 8
palette_collection_style = 'large icons'
palette_creature_style = 0
palette_doodad_style = 'large icons'
palette_item_style = 'listbox'
palette_raw_style = 'listbox'
palette_terrain_style = 'large icons'
use_gui_selection_shadow = false
use_large_choose_item_icons = true
use_large_collection_toolbar = true
use_large_container_icons = true
use_large_doodad_sizebar = true
use_large_house_sizebar = true
use_large_item_sizebar = true
use_large_raw_sizebar = true
use_large_terrain_toolbar = true

[version]
assets_data_dirs = ''
check_signatures = 1
data_directory = ''
extensions_directory = ''
indirectory_installation = 0
use_custom_data_directory = 0
version_id = 40102000

[view]
always_show_zones = true
draw_locked_door = false
ext_house_shader = true
highlight_items = false
highlight_locked_doors = true
show_all_floors = true
show_as_minimap = false
show_autoborder_preview = true
show_blocking = false
show_creatures = true
show_extra = true
show_grid = false
show_houses = true
show_ingame_box = false
show_items = true
show_light_str = true
show_lights = false
show_only_modified_tiles = false
show_only_tileflags = false
show_preview = true
show_shade = true
show_spawns = true
show_special_tiles = true
show_technical_items = true
show_tooltips = true
show_towns = false
show_wall_hooks = false
show_waypoints = true
transparent_floors = false
transparent_items = false

[window]
house_palette_layout = 'name=HousePalette;caption=Houses;state=6293500;dir=2;layer=0;row=0;pos=1;prop=100000;bestw=230;besth=400;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1;floatw_cli=-1;floath_cli=-1'
ingame_preview_layout = ''
ingame_preview_visible = false
minimap_layout = 'name=8811af5069c29835000437350000000b;caption=;state=2099196;dir=4;layer=0;row=0;pos=0;prop=100000;bestw=205;besth=130;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1;floatw_cli=-1;floath_cli=-1'
minimap_visible = false
palette_layout = ''
preferences_window_height = 640
preferences_window_width = 1200
replace_tool_window_height = 850
replace_tool_window_width = 1400
theme = 0
tool_options_layout = 'name=ToolOptions;caption=Tool Options;state=6293500;dir=2;layer=0;row=0;pos=0;prop=100000;bestw=230;besth=300;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1;floatw_cli=-1;floath_cli=-1'
welcome_dialog = true
window_height = 1408
window_maximized = true
window_width = 2576

[[clients]]
clientPath = ''
default = true
name = '7.4'

[[clients]]
clientPath = ''
default = false
name = '7.50'

[[clients]]
clientPath = ''
default = false
name = '7.55'

[[clients]]
clientPath = ''
default = false
name = '7.6'

[[clients]]
clientPath = ''
default = false
name = '7.70'

[[clients]]
clientPath = ''
default = false
name = '7.80'

[[clients]]
clientPath = ''
default = false
name = '7.90'

[[clients]]
clientPath = ''
default = false
name = '7.92'

[[clients]]
clientPath = ''
default = false
name = '8.00'

[[clients]]
clientPath = ''
default = false
name = '8.10'

[[clients]]
clientPath = ''
default = false
name = '8.11'

[[clients]]
clientPath = ''
default = false
name = '8.20 - 8.31'

[[clients]]
clientPath = ''
default = false
name = '8.30'

[[clients]]
clientPath = ''
default = false
name = '8.40'

[[clients]]
clientPath = ''
default = false
name = '8.41'

[[clients]]
clientPath = ''
default = false
name = '8.42'

[[clients]]
clientPath = ''
default = false
name = '8.50'

[[clients]]
clientPath = ''
default = false
name = '8.54'

[[clients]]
clientPath = ''
default = false
name = '8.55'

[[clients]]
clientPath = ''
default = false
name = '8.60'

[[clients]]
clientPath = ''
default = false
name = '8.61'

[[clients]]
clientPath = ''
default = false
name = '8.62'

[[clients]]
clientPath = ''
default = false
name = '8.70'

[[clients]]
clientPath = ''
default = false
name = '8.71'

[[clients]]
clientPath = ''
default = false
name = '8.72'

[[clients]]
clientPath = ''
default = false
name = '8.73'

[[clients]]
clientPath = ''
default = false
name = '9.00'

[[clients]]
clientPath = ''
default = false
name = '9.10'

[[clients]]
clientPath = ''
default = false
name = '9.20 - 9.31'

[[clients]]
clientPath = ''
default = false
name = '9.40'

[[clients]]
clientPath = ''
default = false
name = '9.44'

[[clients]]
clientPath = ''
default = false
name = '9.46'

[[clients]]
clientPath = ''
default = false
name = '9.50'

[[clients]]
clientPath = ''
default = false
name = '9.52'

[[clients]]
clientPath = ''
default = false
name = '9.53'

[[clients]]
clientPath = ''
default = false
name = '9.54'

[[clients]]
clientPath = ''
default = false
name = '9.60'

[[clients]]
clientPath = ''
default = false
name = '9.61'

[[clients]]
clientPath = ''
default = false
name = '9.63'

[[clients]]
clientPath = ''
default = false
name = '9.70'

[[clients]]
clientPath = ''
default = false
name = '9.80'

[[clients]]
clientPath = ''
default = false
name = '9.81'

[[clients]]
clientPath = ''
default = false
name = '9.82'

[[clients]]
clientPath = ''
default = false
name = '9.83'

[[clients]]
clientPath = ''
default = false
name = '9.85'

[[clients]]
clientPath = ''
default = false
name = '9.86'

[[clients]]
clientPath = ''
default = false
name = '10.10'

[[clients]]
clientPath = ''
default = false
name = '10.20'

[[clients]]
clientPath = ''
default = false
name = '10.21'

[[clients]]
clientPath = ''
default = false
name = '10.30'

[[clients]]
clientPath = ''
default = false
name = '10.31'

[[clients]]
clientPath = ''
default = false
name = '10.41'

[[clients]]
clientPath = ''
default = false
name = '10.77'

[[clients]]
clientPath = 'C:\Users\karol\Desktop\Clients\1098'
default = false
name = '10.98'

[[clients]]
clientPath = ''
default = false
name = '10.100'

[[clients]]
clientPath = ''
default = false
name = '12.71 - 12.72'

[[clients]]
clientPath = ''
default = false
name = '12.81'

[[clients]]
clientPath = ''
default = false
name = '12.85'

[[clients]]
clientPath = ''
default = false
name = '12.86'

[[clients]]
clientPath = ''
default = false
name = '12.87'

[[clients]]
clientPath = ''
default = false
name = '12.90'

[[clients]]
clientPath = ''
default = false
name = '13.10'

[[clients]]
clientPath = ''
default = false
name = '13.20'

[[clients]]
clientPath = ''
default = false
name = '12.86-dat'

[[clients]]
clientPath = ''
default = false
name = '12.86-assets'

[[clients]]
clientPath = ''
default = false
name = '7.7-srv'

[[clients]]
clientPath = ''
default = false
name = '10.98dat'

[[clients]]
clientPath = ''
default = false
name = '1098-BlackTek'