//////////////////////////////////////////////////////////////////////
// This file is part of Remere's Map Editor
//////////////////////////////////////////////////////////////////////

#include "app/main.h"

#include "ui/map_statistics_dialog.h"
#include "ui/gui.h"
#include "ui/dialog_util.h"
#include "map/map_statistics.h"
#include "map/map.h"
#include "game/town.h"
#include "game/house.h"
#include "util/image_manager.h"

#include <wx/wx.h>
#include <format>

extern GUI g_gui;

MapStatisticsDialog::MapStatisticsDialog(wxWindow* parent, Map* map) :
	wxDialog(parent, wxID_ANY, "Map Statistics", wxDefaultPosition, wxDefaultSize, wxRESIZE_BORDER | wxCAPTION | wxCLOSE_BOX),
	map(map) {

	g_gui.CreateLoadBar("Collecting data...");
	stats = MapStatisticsCollector::Collect(map);
	g_gui.DestroyLoadBar();

	SetIcon(wxIcon(IMAGE_MANAGER.GetBitmap(ICON_CHART_BAR, wxSize(32, 32))));

	createUI();
}

void MapStatisticsDialog::createUI() {
	std::string text;
	text += std::format("Map statistics for the map \"{}\"\n", map->getMapDescription());

	text += "\tTile data:\n";
	text += std::format("\t\tTotal number of tiles: {}\n", stats.tile_count);
	text += std::format("\t\tNumber of pathable tiles: {}\n", stats.walkable_tile_count);
	text += std::format("\t\tNumber of unpathable tiles: {}\n", stats.blocking_tile_count);
	if (stats.percent_pathable >= 0.0) {
		text += std::format("\t\tPercent walkable tiles: {:.2f}%\n", stats.percent_pathable);
	}
	text += std::format("\t\tDetailed tiles: {}\n", stats.detailed_tile_count);
	if (stats.percent_detailed >= 0.0) {
		text += std::format("\t\tPercent detailed tiles: {:.2f}%\n", stats.percent_detailed);
	}

	text += "\tItem data:\n";
	text += std::format("\t\tTotal number of items: {}\n", stats.item_count);
	text += std::format("\t\tNumber of moveable tiles: {}\n", stats.loose_item_count);
	text += std::format("\t\tNumber of depots: {}\n", stats.depot_count);
	text += std::format("\t\tNumber of containers: {}\n", stats.container_count);
	text += std::format("\t\tNumber of items with Action ID: {}\n", stats.action_item_count);
	text += std::format("\t\tNumber of items with Unique ID: {}\n", stats.unique_item_count);

	text += "\tCreature data:\n";
	text += std::format("\t\tTotal creature count: {}\n", stats.creature_count);
	text += std::format("\t\tTotal spawn count: {}\n", stats.spawn_count);
	if (stats.creatures_per_spawn >= 0) {
		text += std::format("\t\tMean creatures per spawn: {:.2f}\n", stats.creatures_per_spawn);
	}

	text += "\tTown/House data:\n";
	text += std::format("\t\tTotal number of towns: {}\n", stats.town_count);
	text += std::format("\t\tTotal number of houses: {}\n", stats.house_count);
	if (stats.houses_per_town >= 0) {
		text += std::format("\t\tMean houses per town: {:.2f}\n", stats.houses_per_town);
	}
	text += std::format("\t\tTotal amount of housetiles: {}\n", stats.total_house_sqm);
	if (stats.sqm_per_house >= 0) {
		text += std::format("\t\tMean tiles per house: {:.2f}\n", stats.sqm_per_house);
	}
	if (stats.sqm_per_town >= 0) {
		text += std::format("\t\tMean tiles per town: {:.2f}\n", stats.sqm_per_town);
	}

	if (stats.largest_town) {
		text += std::format("\t\tLargest Town: \"{}\" ({} sqm)\n", stats.largest_town->getName(), stats.largest_town_size);
	}
	if (stats.largest_house) {
		text += std::format("\t\tLargest House: \"{}\" ({} sqm)\n", stats.largest_house->name, stats.largest_house_size);
	}

	text += "\n";
	text += std::format("Generated by Remere's Map Editor version {}\n", __RME_VERSION__);

	wxSizer* topsizer = newd wxBoxSizer(wxVERTICAL);
	wxTextCtrl* text_field = newd wxTextCtrl(this, wxID_ANY, wxstr(text), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE | wxTE_READONLY);
	text_field->SetMinSize(wxSize(400, 300));
	topsizer->Add(text_field, wxSizerFlags(1).Expand().Border());

	wxSizer* buttonsizer = newd wxBoxSizer(wxHORIZONTAL);

	wxButton* export_button = newd wxButton(this, wxID_SAVE, "Export as XML");
	export_button->SetBitmap(IMAGE_MANAGER.GetBitmapBundle(ICON_FILE_EXPORT));
	export_button->SetToolTip("Export statistics to an XML file");

	wxButton* closeBtn = newd wxButton(this, wxID_CANCEL, "Close");
	closeBtn->SetBitmap(IMAGE_MANAGER.GetBitmapBundle(ICON_XMARK));
	closeBtn->SetToolTip("Close this window");

	buttonsizer->Add(export_button, wxSizerFlags(0).Center().Border(wxRIGHT, 10));
	buttonsizer->Add(closeBtn, wxSizerFlags(0).Center());

	topsizer->Add(buttonsizer, wxSizerFlags(0).Center().Border());

	SetSizerAndFit(topsizer);
	Centre(wxBOTH);

	Bind(wxEVT_BUTTON, &MapStatisticsDialog::OnExport, this, wxID_SAVE);
	Bind(wxEVT_BUTTON, &MapStatisticsDialog::OnClose, this, wxID_CANCEL);
}

void MapStatisticsDialog::OnExport(wxCommandEvent& event) {
	wxFileDialog saveFileDialog(this, "Export Statistics XML", "", "statistics.xml",
								"XML files (*.xml)|*.xml", wxFD_SAVE | wxFD_OVERWRITE_PROMPT);

	if (saveFileDialog.ShowModal() == wxID_CANCEL)
		return;

	pugi::xml_document doc;
	pugi::xml_node root = doc.append_child("map_statistics");
	root.append_attribute("map_name") = map->getMapDescription().c_str();
	root.append_attribute("generator") = std::format("Remere's Map Editor {}", __RME_VERSION__).c_str();

	// Tile Data
	pugi::xml_node tiles = root.append_child("tiles");
	tiles.append_attribute("total") = stats.tile_count;
	tiles.append_attribute("walkable") = stats.walkable_tile_count;
	tiles.append_attribute("blocking") = stats.blocking_tile_count;
	tiles.append_attribute("detailed") = stats.detailed_tile_count;
	tiles.append_attribute("percent_walkable") = stats.percent_pathable;
	tiles.append_attribute("percent_detailed") = stats.percent_detailed;

	// Item Data
	pugi::xml_node items = root.append_child("items");
	items.append_attribute("total") = stats.item_count;
	items.append_attribute("moveable") = stats.loose_item_count;
	items.append_attribute("depots") = stats.depot_count;
	items.append_attribute("containers") = stats.container_count;
	items.append_attribute("with_aid") = stats.action_item_count;
	items.append_attribute("with_uid") = stats.unique_item_count;

	// Creature Data
	pugi::xml_node creatures = root.append_child("creatures");
	creatures.append_attribute("count") = stats.creature_count;
	creatures.append_attribute("spawns") = stats.spawn_count;
	creatures.append_attribute("per_spawn") = stats.creatures_per_spawn;

	// Town/House Data
	pugi::xml_node locations = root.append_child("locations");
	locations.append_attribute("towns") = stats.town_count;
	locations.append_attribute("houses") = stats.house_count;
	locations.append_attribute("house_sqm") = stats.total_house_sqm;
	locations.append_attribute("houses_per_town") = stats.houses_per_town;
	locations.append_attribute("sqm_per_house") = stats.sqm_per_house;
	locations.append_attribute("sqm_per_town") = stats.sqm_per_town;

	if (stats.largest_town) {
		pugi::xml_node town = locations.append_child("largest_town");
		town.append_attribute("name") = stats.largest_town->getName().c_str();
		town.append_attribute("size") = stats.largest_town_size;
	}

	if (stats.largest_house) {
		pugi::xml_node house = locations.append_child("largest_house");
		house.append_attribute("name") = stats.largest_house->name.c_str();
		house.append_attribute("size") = stats.largest_house_size;
	}

	if (!doc.save_file(saveFileDialog.GetPath().ToStdString().c_str())) {
		wxMessageBox("Failed to save XML file.", "Error", wxOK | wxICON_ERROR, this);
	}
}

void MapStatisticsDialog::OnClose(wxCommandEvent& event) {
	EndModal(wxID_CANCEL);
}
